# Generated by Django 4.2.14 on 2024-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
