# Generated by Django 4.2.14 on 2024-08-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userbankaccount_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
