# Generated by Django 5.0.4 on 2024-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_payment_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
