# Generated by Django 5.0.4 on 2024-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='tran_type',
            field=models.CharField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest'), (4, 'Payment'), (5, 'Transfer')], default='TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest'), (4, 'Payment'), (5, 'Transfer')]),
        ),
    ]
