# Generated by Django 5.0.4 on 2024-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transfer_tran_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('bank_account', 'Bank Account')], max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_account',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
